# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WJPhotoBrowser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'SDWebImage', '~> 3.7.2'
pod 'pop'

  # Pods for WJPhotoBrowser

  target 'WJPhotoBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WJPhotoBrowserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
